"""Scriptronaut QC Checks internal module."""

import time
from typing import Any

import bpy
from bpy.app.handlers import persistent

from .. import constants
from .categories import load_qc_category
from .discovery import get_categories


def set_qc_run_timestamp(context):
    """
    Records the current time as the most recent full QC run.

    Also ignores dependency-graph updates for a short period after
    the QC run so delayed Blender updates do not immediately mark
    the scene as modified.
    """
    
    settings = (
        context.scene.scriptronaut_qc_settings
    )

    settings.last_run_time = str(
        time.time()
    )

    settings.scene_modified_since_qc = False

    # Blender may process dependency graph updates slightly after
    # the QC operator finishes.
    constants.QC_IGNORE_CHANGES_UNTIL = (
        time.time() + 1.0
    )


def get_qc_elapsed_text(settings):
    """
    Returns human-readable time since the last full QC run.
    """
    if not settings.last_run_time:
        return "Not Run Yet"

    try:
        last_time = float(settings.last_run_time)
    except (TypeError, ValueError):
        return "Not Run Yet"

    elapsed_seconds = max(0.0, time.time() - last_time)
    elapsed_minutes = int(elapsed_seconds // 60)

    if elapsed_minutes < 1:
        return "Just now"
    if elapsed_minutes < 60:
        return "1 min ago" if elapsed_minutes == 1 else "{} min ago".format(elapsed_minutes)

    elapsed_hours = elapsed_minutes // 60
    remaining_minutes = elapsed_minutes % 60

    if elapsed_hours < 24:
        if remaining_minutes:
            return "{} hr {} min ago".format(elapsed_hours, remaining_minutes)
        return "{} hr ago".format(elapsed_hours)

    elapsed_days = elapsed_hours // 24
    return "1 day ago" if elapsed_days == 1 else "{} days ago".format(elapsed_days)


def mark_scene_modified_after_qc(
        scene,
        depsgraph,
    ):
    """
    Marks QC results stale when relevant scene data changes
    after the last full QC run.

    Ignores:
        - Changes generated while QC is running.
        - Delayed dependency updates immediately after QC.
        - Changes to the Scene datablock caused by this addon's
          own status properties.
    """
        
    # ---------------------------------------------------------
    # Ignore changes generated by QC itself
    # ---------------------------------------------------------

    if constants.QC_IS_RUNNING:
        return

    # ---------------------------------------------------------
    # Ignore delayed depsgraph updates immediately after QC
    # ---------------------------------------------------------

    if time.time() < constants.QC_IGNORE_CHANGES_UNTIL:
        return

    if scene is None:
        return

    if not hasattr(
        scene,
        "scriptronaut_qc_settings",
    ):
        return

    settings = (
        scene.scriptronaut_qc_settings
    )

    # No QC baseline exists yet.
    if not settings.last_run_time:
        return

    # Already marked dirty; nothing else to do.
    if settings.scene_modified_since_qc:
        return

    # ---------------------------------------------------------
    # Datablocks that can invalidate QC results
    # ---------------------------------------------------------

    relevant_types = (
        bpy.types.Object,
        bpy.types.Mesh,
        bpy.types.Material,
        bpy.types.Image,
        bpy.types.Armature,
        bpy.types.Action,
    )

    for update in depsgraph.updates:
        updated_id = update.id
        if isinstance(
            updated_id,
            relevant_types,
        ):
            settings.scene_modified_since_qc = True
            break


QC_SCENE_MSGBUS_OWNER = object()


def initialize_scene_qc(
        scene,
        window=None,
    ):
    """
    Initializes the QC list for one Scene when its per-scene collection
    is still empty.

    Returns:
        bool:
            True when the Scene is initialized or already populated.
            False when Blender does not yet provide a usable context.
    """
    if scene is None:
        return False

    if not hasattr(
        scene,
        "scriptronaut_qc_settings",
    ):
        return False

    if not hasattr(
        scene,
        "scriptronaut_qc_checks",
    ):
        return False

    settings = (
        scene.scriptronaut_qc_settings
    )

    checks = (
        scene.scriptronaut_qc_checks
    )

    if len(checks) > 0:
        return True

    categories = get_categories(
        settings.folder_path,
        use_json=settings.use_check_settings,
    )

    if not categories:
        checks.clear()
        settings.issues_display = ""
        return True

    # New Scenes inherit the EnumProperty default display, but the update
    # callback does not run because no user-driven category change occurred.
    # Ensure the stored value is valid before explicitly loading it.
    current_category = settings.category

    if current_category not in categories:
        try:
            settings.category = categories[0]
        except (TypeError, ValueError):
            return False

        # The EnumProperty update callback may populate the collection.
        if len(checks) > 0:
            return True

        current_category = settings.category

    # Some newly-created Scenes can visually show the first enum item
    # while the underlying RNA value has not yet caused its update callback
    # to run. At this point we explicitly load whatever valid category is
    # stored rather than waiting for another property change.
    if current_category not in categories:
        return False

    windows = list(
        bpy.context.window_manager.windows
    )

    if not windows:
        return False

    if window is None:
        for candidate in windows:
            if candidate.scene == scene:
                window = candidate
                break

    if window is None:
        window = (
            bpy.context.window
            or windows[0]
        )

    screen = window.screen

    if screen is None:
        return False

    try:
        with bpy.context.temp_override(
            window=window,
            screen=screen,
            scene=scene,
        ):
            success, message = load_qc_category(
                bpy.context
            )

        if not success:
            print(
                "Scriptronaut QC could not initialize Scene '{}': {}".format(
                    scene.name,
                    message,
                )
            )

        return success

    except Exception as error:
        print(
            "Scriptronaut QC could not initialize Scene '{}': {}".format(
                scene.name,
                error,
            )
        )

        return False


def initialize_current_window_scenes_timer():
    """
    Initializes Scenes currently displayed by Blender windows.

    This is scheduled by the RNA message bus when Window.scene changes,
    which happens immediately when the user creates or switches Scenes.
    """
    windows = list(
        bpy.context.window_manager.windows
    )

    if not windows:
        return 0.1

    all_initialized = True

    for window in windows:
        scene = window.scene

        if scene is None:
            continue

        if not initialize_scene_qc(
            scene,
            window=window,
        ):
            all_initialized = False

    redraw_view3d_areas()

    if not all_initialized:
        return 0.1

    return None


def refresh_current_window_qc_categories_timer():
    """
    Reloads the currently selected QC category for every visible Scene
    after the registered check-pack list changes.
    """
    windows = list(
        bpy.context.window_manager.windows
    )

    if not windows:
        return 0.1

    retry = False

    for window in windows:
        scene = window.scene

        if scene is None:
            continue

        if not hasattr(
            scene,
            "scriptronaut_qc_settings",
        ):
            retry = True
            continue

        if not hasattr(
            scene,
            "scriptronaut_qc_checks",
        ):
            retry = True
            continue

        screen = window.screen

        if screen is None:
            retry = True
            continue

        try:
            with bpy.context.temp_override(
                window=window,
                screen=screen,
                scene=scene,
            ):
                success, message = load_qc_category(
                    bpy.context
                )

            if not success:
                print(
                    (
                        "Scriptronaut QC could not refresh Scene "
                        "'{}' after a pack change: {}"
                    ).format(
                        scene.name,
                        message,
                    )
                )

        except Exception as error:
            print(
                (
                    "Scriptronaut QC could not refresh Scene "
                    "'{}' after a pack change: {}"
                ).format(
                    scene.name,
                    error,
                )
            )

            retry = True

    redraw_view3d_areas()

    if retry:
        return 0.1

    return None


def notify_check_pack_registry_changed():
    """
    Schedules a deferred category reload after a check pack is
    registered or unregistered.
    """
    if not bpy.app.timers.is_registered(
        refresh_current_window_qc_categories_timer
    ):
        bpy.app.timers.register(
            refresh_current_window_qc_categories_timer,
            first_interval=0.01,
        )


def notify_window_scene_changed():
    """
    Message-bus callback fired when a Blender window changes Scene.

    RNA message-bus callbacks do not receive a reliable UI context, so the
    actual initialization is deferred to a short timer tick.
    """
    if not bpy.app.timers.is_registered(
        initialize_current_window_scenes_timer
    ):
        bpy.app.timers.register(
            initialize_current_window_scenes_timer,
            first_interval=0.01,
        )


def register_scene_change_listener():
    """
    Subscribes to Blender Window.scene changes.
    """
    bpy.msgbus.clear_by_owner(
        QC_SCENE_MSGBUS_OWNER
    )

    bpy.msgbus.subscribe_rna(
        key=(
            bpy.types.Window,
            "scene",
        ),
        owner=QC_SCENE_MSGBUS_OWNER,
        args=(),
        notify=notify_window_scene_changed,
        options={
            "PERSISTENT",
        },
    )


def unregister_scene_change_listener():
    """
    Removes the Window.scene message-bus subscription.
    """
    bpy.msgbus.clear_by_owner(
        QC_SCENE_MSGBUS_OWNER
    )

    if bpy.app.timers.is_registered(
        initialize_current_window_scenes_timer
    ):
        bpy.app.timers.unregister(
            initialize_current_window_scenes_timer
        )


def initialize_new_scene_qc(
        scene,
        depsgraph,
    ):
    """
    Dependency-graph fallback for newly created Scenes.

    The Window.scene message bus is the primary mechanism because an empty
    newly-created Scene may not produce a dependency-graph update immediately.
    """
    initialize_scene_qc(
        scene
    )


def redraw_view3d_areas():
    """
    Requests redraw for every View3D area.
    """
    try:
        for window in bpy.context.window_manager.windows:
            screen = window.screen

            if screen is None:
                continue

            for area in screen.areas:
                if area.type == "VIEW_3D":
                    area.tag_redraw()

    except Exception:
        pass


def redraw_qc_status_timer():
    """
    Redraws View3D areas so elapsed QC time updates while idle.
    """
    redraw_view3d_areas()

    return 30.0


def initialize_qc_checks_timer():
    """
    Initialize the check list after Blender has a usable window context.

    During startup or extension reload, Blender may call this timer before
    bpy.context.window exists. Returning a positive number asks Blender
    to retry instead of permanently ending the timer with an empty list.
    """
    if not bpy.context.window_manager.windows:
        return 0.25

    initialized = initialize_qc_checks_after_load()

    if not initialized:
        return 0.25

    return None


@persistent
def initialize_qc_checks_after_load(_dummy=None):
    """
    Initializes the QC category and script list after a Blender file loads.
    """
    windows = list(
        bpy.context.window_manager.windows
    )

    if not windows:
        return False

    window = (
        bpy.context.window
        or windows[0]
    )

    screen = window.screen

    for scene in bpy.data.scenes:
        if not hasattr(
            scene,
            "scriptronaut_qc_settings",
        ):
            continue

        settings = (
            scene.scriptronaut_qc_settings
        )

        checks = (
            scene.scriptronaut_qc_checks
        )

        categories = get_categories(
            settings.folder_path,
            use_json=settings.use_check_settings,
        )

        if not categories:
            checks.clear()
            settings.issues_display = ""
            continue

        if settings.category not in categories:
            settings.category = categories[0]

        with bpy.context.temp_override(
            window=window,
            screen=screen,
            scene=scene,
        ):
            load_qc_category(
                bpy.context
            )

    return True
