"""Scriptronaut QC Checks internal module."""

import time
from typing import Any

import bpy
from bpy.app.handlers import persistent

from .. import constants
from .categories import load_qc_category
from .discovery import get_categories

def set_qc_run_timestamp(context):
    """
    Records the current time as the most recent full QC run.

    Also ignores dependency-graph updates for a short period after
    the QC run so delayed Blender updates do not immediately mark
    the scene as modified.
    """
    
    settings = (
        context.scene.scriptronaut_qc_settings
    )

    settings.last_run_time = str(
        time.time()
    )

    settings.scene_modified_since_qc = False

    # Blender may process dependency graph updates slightly after
    # the QC operator finishes.
    constants.QC_IGNORE_CHANGES_UNTIL = (
        time.time() + 1.0
    )

def get_qc_elapsed_text(settings):
    """
    Returns human-readable time since the last full QC run.
    """
    if not settings.last_run_time:
        return "Not Run Yet"

    try:
        last_time = float(settings.last_run_time)
    except (TypeError, ValueError):
        return "Not Run Yet"

    elapsed_seconds = max(0.0, time.time() - last_time)
    elapsed_minutes = int(elapsed_seconds // 60)

    if elapsed_minutes < 1:
        return "Just now"
    if elapsed_minutes < 60:
        return "1 min ago" if elapsed_minutes == 1 else "{} min ago".format(elapsed_minutes)

    elapsed_hours = elapsed_minutes // 60
    remaining_minutes = elapsed_minutes % 60

    if elapsed_hours < 24:
        if remaining_minutes:
            return "{} hr {} min ago".format(elapsed_hours, remaining_minutes)
        return "{} hr ago".format(elapsed_hours)

    elapsed_days = elapsed_hours // 24
    return "1 day ago" if elapsed_days == 1 else "{} days ago".format(elapsed_days)

def mark_scene_modified_after_qc(
        scene,
        depsgraph,
    ):
    """
    Marks QC results stale when relevant scene data changes
    after the last full QC run.

    Ignores:
        - Changes generated while QC is running.
        - Delayed dependency updates immediately after QC.
        - Changes to the Scene datablock caused by this addon's
          own status properties.
    """
        
    # ---------------------------------------------------------
    # Ignore changes generated by QC itself
    # ---------------------------------------------------------

    if constants.QC_IS_RUNNING:
        return

    # ---------------------------------------------------------
    # Ignore delayed depsgraph updates immediately after QC
    # ---------------------------------------------------------

    if time.time() < constants.QC_IGNORE_CHANGES_UNTIL:
        return

    if scene is None:
        return

    if not hasattr(
        scene,
        "scriptronaut_qc_settings",
    ):
        return

    settings = (
        scene.scriptronaut_qc_settings
    )

    # No QC baseline exists yet.
    if not settings.last_run_time:
        return

    # Already marked dirty; nothing else to do.
    if settings.scene_modified_since_qc:
        return

    # ---------------------------------------------------------
    # Datablocks that can invalidate QC results
    # ---------------------------------------------------------

    relevant_types = (
        bpy.types.Object,
        bpy.types.Mesh,
        bpy.types.Material,
        bpy.types.Image,
        bpy.types.Armature,
        bpy.types.Action,
    )

    for update in depsgraph.updates:
        updated_id = update.id
        if isinstance(
            updated_id,
            relevant_types,
        ):
            settings.scene_modified_since_qc = True
            break

def redraw_qc_status_timer():
    """
    Redraws View3D areas so elapsed QC time updates while idle.
    """
    try:
        for window in bpy.context.window_manager.windows:
            screen = window.screen
            if screen is None:
                continue
            for area in screen.areas:
                if area.type == "VIEW_3D":
                    area.tag_redraw()
    except Exception:
        pass

    return 30.0

def initialize_qc_checks_timer():
    """
    Timer wrapper used when enabling the addon.
    """
    initialize_qc_checks_after_load()
    return None

def initialize_qc_checks_after_load(_dummy=None):
    """
    Initializes the QC category and script list after a Blender file loads.
    """
    for scene in bpy.data.scenes:
        if not hasattr(scene, "scriptronaut_qc_settings"):
            continue

        settings = scene.scriptronaut_qc_settings
        checks = scene.scriptronaut_qc_checks

        categories = get_categories(
            settings.folder_path,
            use_json=settings.use_check_settings,
        )

        if not categories:
            checks.clear()
            settings.issues_display = ""
            continue

        if settings.category not in categories:
            settings.category = categories[0]

        # Load using a context override for this scene.
        window = bpy.context.window

        if window is not None:
            with bpy.context.temp_override(
                window=window,
                scene=scene,
            ):
                load_qc_category(bpy.context)
