schema_version = "1.0.0"

id = "scriptronaut_qc_checker"
version = "1.0.0"
name = "Scriptronaut QC Checker"
tagline = "Run categorized quality-control sanity checks in Blender"

maintainer = "Scriptronaut"
website = "https://scriptronaut.com"

type = "add-on"
tags = [
    "3D View",
    "Pipeline",
    "Workflow",
]

blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]


[permissions]
files = true